package View;

import Controller.CurrencyController;
import Dtos.CurrencyRequest;
import Service.FlagService;
import Service.IpDataUserService;
import java.awt.Image;
import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;

/**
 *
 * @author tarri
 */
import java.util.Currency;
import java.util.Locale;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

public class JfrmConvertionView extends javax.swing.JFrame {

    /**
     * Creates new form JfrmConvertionView
     */
    public JfrmConvertionView() {
        initComponents();
        getCurrencyCode();
    }

    private void getCurrencyCode() {

        Set<Currency> c = Currency.getAvailableCurrencies();
        c.stream()
                .filter(currency -> !currency.getDisplayName().contains("("))
                .forEach(
                        curren -> cbxCurrencyCode.addItem(curren.getDisplayName().toUpperCase() + " (" + curren.getCurrencyCode().toUpperCase() + ")"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtMoney = new javax.swing.JTextField();
        cbxCurrencyCode = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblImgCountry = new javax.swing.JLabel();
        lblMontoConvertido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-logo.jpg"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 87, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(253, 116, 80));
        jLabel1.setText("MULTY CURRENCY");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 47, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 47, 14, 270));

        txtMoney.setBackground(new java.awt.Color(255, 255, 255));
        txtMoney.setBorder(null);
        jPanel2.add(txtMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 200, 40));

        cbxCurrencyCode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- SELECCIONE ---" }));
        cbxCurrencyCode.setToolTipText("");
        jPanel2.add(cbxCurrencyCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 270, 50));

        jButton1.setText("Convertir moneda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 130, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(116, 162, 249));
        jLabel2.setText("Ingresar pais de moneda de conversion");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(116, 162, 249));
        jLabel4.setText("Ingresar monto");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 200, -1));
        jPanel2.add(lblImgCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 40, 30));
        jPanel2.add(lblMontoConvertido, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 80, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 650, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            double money = Double.parseDouble(txtMoney.getText());
            String currency = cbxCurrencyCode.getSelectedItem().toString();
            int currencyLength = currency.indexOf("(");
            String codeCurrency = currency.substring(currencyLength + 1, currency.length() - 1);

            IpDataUserService idus = new IpDataUserService();
            System.out.println(idus.getLocation());

            FlagService fds = new FlagService();
            System.out.println(fds.getFlagByCountry(idus.getLocation().country()));
            System.out.println(fds.getFlagByCountry(idus.getLocation().country()).cca2());

            showFlagImage(fds.getFlagByCountry(idus.getLocation().country()).png()); // Asumiendo que png es la URL de la imagen

            Locale locale = new Locale("", fds.getFlagByCountry(idus.getLocation().country()).cca2()); // Español, Perú
            Currency currencys = Currency.getInstance(locale);

            // Obtener la abreviatura de la moneda
            String currencyCode = currencys.getCurrencyCode();
            System.out.println("La abreviatura de la moneda de Perú es: " + currencyCode);

            CurrencyRequest request = new CurrencyRequest(currencyCode, codeCurrency, money);

            CurrencyController controller = new CurrencyController();
            lblMontoConvertido.setText(""+controller.convertCurrency(request).money());

        } catch (IOException | InterruptedException ex) {
            Logger.getLogger(JfrmConvertionView.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void showFlagImage(String imageUrl) {
        try {
            // Usar HttpClient para descargar la imagen como InputStream
            HttpClient client = HttpClient.newHttpClient();
            HttpRequest request = HttpRequest.newBuilder()
                    .uri(URI.create(imageUrl))
                    .build();

            HttpResponse<InputStream> response = client.send(request, HttpResponse.BodyHandlers.ofInputStream());
            InputStream imageStream = response.body();

            // Leer la imagen desde el InputStream
            Image image = ImageIO.read(imageStream);

            if (image != null) {
                // Redimensionar la imagen para que encaje en el JLabel
                Image scaledImage = image.getScaledInstance(lblImgCountry.getWidth(), lblImgCountry.getHeight(), Image.SCALE_SMOOTH);

                // Establecer la imagen en el JLabel
                lblImgCountry.setIcon(new ImageIcon(scaledImage));
            } else {
                lblImgCountry.setText("No se pudo cargar la imagen");
            }

            // Cerrar el InputStream
            imageStream.close();
        } catch (IOException | InterruptedException e) {
            lblImgCountry.setText("Error al descargar la imagen");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmConvertionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmConvertionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmConvertionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmConvertionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrmConvertionView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxCurrencyCode;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblImgCountry;
    private javax.swing.JLabel lblMontoConvertido;
    private javax.swing.JTextField txtMoney;
    // End of variables declaration//GEN-END:variables
}
