package View;

import Controller.CountryController;
import Controller.CurrencyController;
import Dtos.CurrencyRequest;
import Dtos.FlagDtoResponse;
import Service.FlagService;
import Service.IpDataUserService;
import java.awt.Image;
import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;

/**
 *
 * @author tarri
 */
import java.util.Currency;
import java.util.Locale;
import java.util.Set;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

public class JfrmConvertionView extends javax.swing.JFrame {

    private String currencyCode;

    /**
     * Creates new form JfrmConvertionView
     */
    public JfrmConvertionView() {
        initComponents();
        getCurrencyCode();
        showImgCountry();

    }

    // Obtenemos y mostramos los nombres y la moneda de los paises correspondientes
    private void getCurrencyCode() {

        Set<Currency> c = Currency.getAvailableCurrencies();
        c.stream()
                .filter(currency -> !currency.getDisplayName().contains("("))
                .sorted((c1, c2) -> c1.getDisplayName().compareTo(c2.getDisplayName())) // Ordenar por nombre de visualización
                .forEach(
                        curren -> cbxCurrencyCode.addItem(curren.getDisplayName().toUpperCase() + " (" + curren.getCurrencyCode().toUpperCase() + ")"));

    }

    private void showImgCountry() {

        CountryController cc = new CountryController();
        FlagDtoResponse fg = cc.getFlag();
        try {
            // Usar HttpClient para descargar la imagen como InputStream
            HttpClient client = HttpClient.newHttpClient();
            HttpRequest request = HttpRequest.newBuilder()
                    .uri(URI.create(fg.png()))
                    .build();

            HttpResponse<InputStream> response = client.send(request, HttpResponse.BodyHandlers.ofInputStream());
            InputStream imageStream = response.body();

            // Leer la imagen desde el InputStream
            Image image = ImageIO.read(imageStream);

            if (image != null) {
                // Redimensionar la imagen para que encaje en el JLabel
                Image scaledImage = image.getScaledInstance(lblImgCountry.getWidth(), lblImgCountry.getHeight(), Image.SCALE_SMOOTH);

                // Establecer la imagen en el JLabel
                lblImgCountry.setIcon(new ImageIcon(scaledImage));

                Locale peruLocale = Locale.of("es", fg.cca2());
                Currency currency = Currency.getInstance(peruLocale);
                currencyCode = currency.getCurrencyCode();
                lblMonedaCountry.setText(currency.getSymbol(peruLocale));
            } else {
                lblImgCountry.setText("No se pudo cargar la imagen");
            }

            // Cerrar el InputStream
            imageStream.close();
        } catch (IOException | InterruptedException e) {
            lblImgCountry.setText("Error al descargar la imagen");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtMoney = new javax.swing.JTextField();
        cbxCurrencyCode = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblImgCountry = new javax.swing.JLabel();
        lblMontoConvertido = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblMonedaCountry = new javax.swing.JLabel();
        lblSymbolReturn = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-logo.jpg"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(44, 44, 44));
        jLabel1.setText("MULTY CURRENCY");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 30, 230));

        txtMoney.setBackground(new java.awt.Color(255, 255, 255));
        txtMoney.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        txtMoney.setForeground(new java.awt.Color(0, 0, 0));
        txtMoney.setBorder(null);
        jPanel2.add(txtMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 200, 40));

        cbxCurrencyCode.setBackground(new java.awt.Color(255, 255, 255));
        cbxCurrencyCode.setForeground(new java.awt.Color(0, 0, 0));
        cbxCurrencyCode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- SELECCIONE ---" }));
        cbxCurrencyCode.setToolTipText("");
        jPanel2.add(cbxCurrencyCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 400, 50));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Convertir moneda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 400, 40));

        jLabel2.setForeground(new java.awt.Color(60, 60, 60));
        jLabel2.setText("Moneda de conversion");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));
        jPanel2.add(lblImgCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 40, 30));
        jPanel2.add(lblMontoConvertido, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 80, 40));

        jPanel3.setBackground(new java.awt.Color(207, 247, 211));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(155, 206, 169));
        jLabel4.setText("Ingresar monto");
        jPanel3.add(jLabel4);

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 110, 30));

        lblMonedaCountry.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMonedaCountry.setText("s/");
        jPanel2.add(lblMonedaCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        lblSymbolReturn.setText("Monto de conversion:");
        jPanel2.add(lblSymbolReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 120, 20));

        btnLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cleaData.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(null);
        btnLimpiar.setContentAreaFilled(false);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 100, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        double money = Double.parseDouble(txtMoney.getText());
        String currency = cbxCurrencyCode.getSelectedItem().toString();
        int currencyLength = currency.indexOf("(");
        String codeCurrency = currency.substring(currencyLength + 1, currency.length() - 1);

        CurrencyRequest request = new CurrencyRequest(currencyCode, codeCurrency, money);
        CurrencyController controller = new CurrencyController();
        lblMontoConvertido.setText("" + controller.convertCurrency(request).money());


    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        cleanData();

    }//GEN-LAST:event_btnLimpiarActionPerformed

    public void cleanData() {

        txtMoney.setText("");
        lblMontoConvertido.setText("");
        cbxCurrencyCode.setSelectedIndex(0);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmConvertionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmConvertionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmConvertionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmConvertionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrmConvertionView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cbxCurrencyCode;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblImgCountry;
    private javax.swing.JLabel lblMonedaCountry;
    private javax.swing.JLabel lblMontoConvertido;
    private javax.swing.JLabel lblSymbolReturn;
    private javax.swing.JTextField txtMoney;
    // End of variables declaration//GEN-END:variables
}
